[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PORT = "8000" }

# Tell Railway to ignore frontend files and focus on backend
[[build.watchPatterns]]
pattern = "backend/**"
ignore = false

[[build.watchPatterns]]
pattern = "frontend/**"
ignore = true

[[build.watchPatterns]]
pattern = "spark-realm/**"
ignore = true

[[build.watchPatterns]]
pattern = "PulseCheckMobile/**"
ignore = true

[[build.watchPatterns]]
pattern = "node_modules/**"
ignore = true 