[build]
builder = "nixpacks"

[deploy]
startCommand = "python startup_v2.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PORT = "8000" }

# Force rebuild by changing deployment config
[env]
REBUILD_TRIGGER = "2024-01-30-startup-v2-force-rebuild" 